### ISSUE TITLE
Multiple Add operations fail

### ISSUE THREAD

**Issue by mwhitesi** [Sheikhizadeh/pantools#5]
Hi,

I have been unable to call the add operation more than once.  The first time is successful, but then on the second call, it fails. E.g.

java -Xmx8g -jar /home/matt/pantools/dist/pantools.jar build $DBPATH $INPUTFILE 31
   ... works ok
java -Xmx8g -jar /home/matt/pantools/dist/pantools.jar add $DBPATH $INPUTFILE2
   ... works ok
java -Xmx8g -jar /home/matt/pantools/dist/pantools.jar add $DBPATH $INPUTFILE3

Gives the following error output:

------------------------------- PanTools -------------------------------
Reading 5 genome(s)...
Sequence 8/8 of genome 11 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/10.fasta					
Sequence 8/8 of genome 12 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/11.fasta					
Sequence 8/8 of genome 13 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/12.fasta					
Sequence 8/8 of genome 14 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/13.fasta					
Sequence 8/8 of genome 15 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/14.fasta					
/media/poolhouse/workspace/l_amr/data/load_test/db/databases/index.db/old_index
Failed to make index!

If I delete the old_index directory and try again, I get this error:

------------------------------- PanTools -------------------------------
Reading 5 genome(s)...
Sequence 12/12 of genome 16 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/15.fasta    				
Sequence 12/12 of genome 17 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/16.fasta    				
Sequence 12/12 of genome 18 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/17.fasta    				
Sequence 12/12 of genome 19 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/18.fasta    				
Sequence 12/12 of genome 20 : /media/poolhouse/workspace/l_amr/data/load_test/fasta/19.fasta    				
Indexing 52053215 kmers...                    
Running KMC2...                      
75767740 new kmers generated.                    
Updating kmer index...                    
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.putLong(DirectByteBuffer.java:806)
	at index.IndexDatabase.put_pointer(IndexDatabase.java:511)
	at index.IndexDatabase.<init>(IndexDatabase.java:356)
	at pangenome.SequenceLayer.add(SequenceLayer.java:213)
	at pantools.Pantools.main(Pantools.java:137)

thanks for your help.

matt

**Comment by Sheikhizadeh** [comment]
Thank you Matt for letting me know. I sorted it out.
